server.port: 9101

spring:
  application.name: tree-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: qwerty
#    testWhileIdle: true
#    validationQuery: SELECT 1

#  jpa.generate-ddl: true
  jpa:
    show-sql: true
    properties.hibernate.format_sql: true
---
spring:
  profiles: docker
  datasource.url: jdbc:postgresql://postgres-db:5432/postgres
---


